version: "3"

services:
  #  nginx:
  #    container_name: nginx
  #    image: nginx
  #    ports:
  #      - "80:80"
  #    volumes:
  #      - ./backend/nginx/conf.d:/etc/nginx/conf.d
  #    depends_on:
  #      - backend
  #    networks:
  #      - mohaeng_network

  db:
    container_name: my_sql
    image: mysql
    environment:
      MYSQL_DATABASE: testdb
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - ./db:/var/lib/mysql:rw
    networks:
      - mohaeng_network
    ports:
      - "3306:3306"
    restart: always

  backend:
    build:
      context: backend/
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - mohaeng_network
    container_name: "backend"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://my_sql:3306/testdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234

#  frontend:
#    build:
#      context: frontend/
#      dockerfile: Dockerfile
#    restart: always
#    ports:
#      - "3000:3000"
#    container_name: "frontend"
#    depends_on:
#      - backend
#    networks:
#      - mohaeng_network

networks:
  mohaeng_network: