package com.mohaeng.backend.exception;

public enum ErrorCode {
    NOT_EXIST_ACCESS_TOKEN,
    EXPIRED_ACCESS_TOKEN,
    INVALID_TOKEN_FORMAT,
    EXPIRED_REFRESH_TOKEN,
    NOT_EXIST_REFRESH_TOKEN,
    REFRESH_TOKEN_NOT_FOUND,
    DUPLICATED_REFRESH_TOKEN,
    DUPLICATED_MEMBER,
    DUPLICATED_NICKNAME,
    MEMBER_NOT_FOUND,

    NOT_EXIST_USER_DELETE,

    DUPLICATED_REVIEW,
    REVIEW_NOT_FOUND,
    BLANK_REVIEW_CONTENT,
    INVALID_REVIEW_RATING,

    PLACE_NOT_FOUND,

    COURSE_NOT_FOUND,
    ALREADY_LIKED_COURSE,
    ALREADY_BOOKMARK_COURSE,
    NOT_EXIST_COURSE_LIKES,
    NOT_EXIST_COURSE_BOOKMARK,
    NOT_EXIST_PLACE_BOOKMARK,
    NOT_MATCH_MEMBER_AND_COURSE,
    INVALID_KEYWORD_PLACE_IN_COURSE,
    NOT_MATCH_MEMBER_AND_COURSE_BOOKMARK,
    NOT_MATCH_MEMBER_AND_PLACE_BOOKMARK,

    PERMISSION_DENIED,

    INVALID_REQUEST_BODY,
    INVALID_SEARCH_PARAM,
    INVALID_PATH_VARIABLE

}
